# .github/labeler.yml

# Label for bug-related changes
 bug:
    - bug
    - fix

# Label for document-related changes
Docs:
   - docs
   - documentatio
   - Text File

# Label for enhancement-related changes
  enhancement:
    - feature
    - enhancement

# Label for UI-related changes
  UI:
    - UI/UX
    - User Interface
    - Web Design

# Label for Frontend-related changes
  Frontend:
    - UI/UX
    - User Interface
    - Web Design

# Label for Backend-related changes
  Backend:
    - Schema
    - Data base
